export const MUSCLE_GROUPS = ["chest", "arms", "abdominal", "leg", "shoulder"];

export const EXERCISES = [
  { name: "Bench press", group: "chest" },
  { name: "Push-up", group: "chest" },
  { name: "Push up", group: "chest" },
  { name: "Pull-up", group: "arm" },
  { name: "Pull up", group: "arm" },
  { name: "Biceps curl", group: "arm" },
  { name: "Triceps dip", group: "arm" },
  { name: "Crunch", group: "abdominal" },
  { name: "Leg raise", group: "abdominal" },
  { name: "Squat", group: "leg" },
  { name: "Lunge", group: "leg" },
  { name: "Deadlift", group: "leg" },
  { name: "Shoulder press", group: "shoulder" },
  { name: "Lateral raise", group: "shoulder" },
  { name: "Front raise", group: "shoulder" },
  { name: "Dead hang", group: "arm" },
  { name: "Russian twist", group: "abdominal" },
  { name: "Leg press", group: "leg" },
  { name: "Calf raise", group: "leg" },
  { name: "Arnold press", group: "shoulder" },
  { name: "Chin-up", group: "arm" },
  { name: "Chin up", group: "arm" },
  { name: "Plank", group: "abdominal" },
  { name: "Hip thrust", group: "leg" },
  { name: "Reverse fly", group: "shoulder" },
  { name: "Side raise", group: "shoulder" },
  { name: "Incline bench press", group: "chest" },
  { name: "Hammer curl", group: "arm" },
  { name: "Skull crusher", group: "arm" },
  { name: "Mountain climber", group: "abdominal" },
  { name: "Step-up", group: "leg" },
  { name: "Box jump", group: "leg" },
  { name: "Clean and press", group: "shoulder" },
  { name: "Dip", group: "arm" },
  { name: "Flutter kick", group: "abdominal" },
  { name: "Romanian deadlift", group: "leg" },
  { name: "Upright row", group: "shoulder" },
  // Add more exercises and their muscle group associations here
];
